// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSV6-M7xXxbj3sWsdwUPWgtHYjRQ0FObw',
    appId: '1:522560156595:web:a13f964963e0dd820791c6',
    messagingSenderId: '522560156595',
    projectId: 'crudriverpod-9432d',
    authDomain: 'crudriverpod-9432d.firebaseapp.com',
    storageBucket: 'crudriverpod-9432d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhIJIsmHCAkRxukp6MOVCbgA-50wYOxY',
    appId: '1:522560156595:android:f51deed3da7c537d0791c6',
    messagingSenderId: '522560156595',
    projectId: 'crudriverpod-9432d',
    storageBucket: 'crudriverpod-9432d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjdlH71XQmg2xDzqwpcHLiFvcNoAHf_o',
    appId: '1:522560156595:ios:60368a20d980e9760791c6',
    messagingSenderId: '522560156595',
    projectId: 'crudriverpod-9432d',
    storageBucket: 'crudriverpod-9432d.appspot.com',
    iosBundleId: 'com.example.crud',
  );
}
